a='helloo there there'
print(a.endswith("re"))
print(a.endswith("oo"))
print(a.endswith("lo"))
print(a.startswith("lo"))
print(a.startswith("he"))
print(a.capitalize())
print(a.title())
print(a.find("te"))
print(a.find("the"))
print(a)
print(a.replace('the',"Ere"))
print(a)
print(a.replace('te',"Ere"))
print(a)
print("Namaste\"hello\"")
print("Namaste\\")